behaviors:
  Miner:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    max_steps: 60000000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 10
    checkpoint_interval: 5000000
    self_play:
      window: 5
      play_against_latest_model_ratio: 0.5
      save_steps: 100000
      swap_steps: 100000
      team_change: 2000000

environment_parameters:
  hitsNeeded:
    curriculum:
      - name: Coins # The '-' is important as this is a list
        completion_criteria:
          measure: reward 
          behavior: Miner
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.0063
          require_reset: true
        value: 0
      - name: OneHit # This is the start of the second lesson
        completion_criteria:
          measure: reward 
          behavior: Miner
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.0063
          require_reset: true
        value: 1
      - name: FinalLesson
        value: -1

checkpoint_settings:
  results_dir: Assets/results